name: Access secret key

on: [pull_request]

jobs:
  access-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Decode secret
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
          --output $HOME/secrets/my_secret.json public_secret.json.gpg
      - name: log secret
        run: cat $HOME/secrets/my_secret.json
      - name: log home
        run: |
          echo $HOME
          echo "$HOME"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
