name: Create issue from commit

on:
  pull_request:
    types: [opened]

env:
  MY_ENV: my env variable

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: create issue using REST API
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.GITHUB_REPOSITORY }}/issues
            -d '{"title": "This issue is created from worflow by REST API", "body": "Body of the issue","labels":["bug"]}'
