name: Run Worflow on matrix

on: [pull_request]

jobs:
  run-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [6, 7, 8]
        exclude:
          - os: ubuntu-latest
            node-version: 7
          - os: windows-latest
            node-version: 8
        include:
          - os: ubuntu-latest
            node-version: 10
            is_ubuntu_10: true
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_10: ${{ matrix.is_ubuntu_10 }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node node-version
        run: |
          node -v
          echo $IS_UBUNTU_10
