name: Push random file

on:
  pull_request:
    types: [opened]

jobs:
  push-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a 
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.name 'help-bot'
          git config --global user.email 'help-bot@bot.com'
          git fetch
          git checkout $GITHUB_HEAD_REF
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a 
          git add .
          git commit -m 'random file'
          git push
