name: Run Github Actions

on: [push]

jobs:
  run-github-action:
    name: Run action from github actions marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        uses: actions/hello-world-javascript-action@v1.1
      - name: Hello world action with inputs
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Eugene
      - name: Log last greeting time
        run: echo ${{ steps.greet.outputs.time }}
  console-log-env:
    name: Console log environment variables
    runs-on: ubuntu-latest
    steps:
      - name: github
        run: echo ${{ github }}
      - name: token
        run: echo ${{ steps }}
      - name: "github variable"
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          printenv
