name: Scheduled Workflow

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  log-hello:
    name: Console log Hello world
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Console log
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Eugene
